node 'ento.ak.local' {
  file { '/etc/hostname':
    content => "ento.ak.local\n",
    mode => 0644,
    owner => 'root',
    group => 'root',
  }

  file { '/etc/sysconfig/network-scripts/ifcfg-eth0':
    content => "# Generated by parse-kickstart\nIPV6INIT=yes\nDHCP_HOSTNAME=ento.ak.local\nBOOTPROTO=none\nDEVICE=eth0\nONBOOT=yes\nPEERDNS=yes\nPEERROUTES=yes\nIPADDR=192.168.2.12\nNETMASK=255.255.255.0\nGATEWAY=192.168.2.1\nDNS1=192.168.2.11\nUUID=66451e09-dbfa-4451-8eaf-774b7152a5c9\n",
    mode => 0644,
    owner => 'root',
    group => 'root',
  }
}
